name: Demo to create automatic PR
on: 
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Hello world action step
        uses: ./
        id: hello
        with:
          who-to-greet: 'Harish'
      # Use the output from the `hello` step
      - name: Get the version
        run: echo "The version to be updated is ${{ steps.hello.outputs.version }}"

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: "demo for auto pr"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show update PR creation from ${{steps.hello.outputs.version}} to 0.24.0
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true