name: Demo to create automatic PR
on: 
  push:
    branches:
      - main

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update version information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Hello world action step
        uses: ./
        id: hello
        with:
          who-to-greet: 'Harish'
      - name: Get the version

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: "demo for update pr"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show update PR creation ${{ steps.hello.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          